LuposX/KonfiguratorFuerOSMDaten

src/osm_configurator/model/parser/osm_data_handler.py
src_tests/unittests/osm_configurator/model/parser/test_osm_data_parser.py

We have in the tagfilterphase dataframe one row per category for each category it applies to.

Changes of what dataframes are made of

---

src_tests/unittests/osm_configurator/model/project/test_data_visualizer.py

removed unsused improts which broke model

removed unused imports

---

src/osm_configurator/model/project/calculation/paralellization/work.py
src/osm_configurator/model/project/calculation/paralellization/work_manager.py
src/osm_configurator/model/project/calculation/paralellization/worker.py
src_tests/libaryTests/test_memory_usage.ipynb
src_tests/unittests/osm_configurator/model/project/calculation/parallelization/test_work_manager.py

implemented work_manager and work, which allow multiprocessing

Multiprocessing

---

src/osm_configurator/control/aggregation_controller.py
src/osm_configurator/control/cut_out_controller.py

Cut out and aggregation controller

---

src/osm_configurator/control/category_controller.py
src/osm_configurator/control/category_controller_interface.py
src/osm_configurator/control/export_controller.py
src/osm_configurator/model/project/configuration/category_manager.py

Category and export controller

---

src/osm_configurator/control/project_controller.py
src/osm_configurator/control/project_controller_interface.py
src/osm_configurator/model/application/application.py
src/osm_configurator/model/application/application_interface.py

Project controller

---

src/osm_configurator/model/parser/category_parser.py
src/osm_configurator/model/project/configuration/attractivity_attribute.py
src/osm_configurator/model/project/configuration/category.py
src/osm_configurator/model/project/configuration/category_manager.py
src/osm_configurator/model/project/configuration/default_categories.py
src_tests/definitions.py
src_tests/unittests/osm_configurator/model/project/calculation/test_aggregation_phase.py
src_tests/unittests/osm_configurator/model/project/test_project_io_handler.py
src_tests/unittests/osm_configurator/model/project/test_project_saver.py

added default values 
changed constructor of categories as the view needs it

Model changes add default

---

src/osm_configurator/model/application/application.py
src/osm_configurator/model/application/application_settings.py
src_tests/definitions.py
src_tests/unittests/osm_configurator/model/application/test_application_settings_saver.py
src_tests/unittests/osm_configurator/model/project/calculation/test_calculation_manager.py
src_tests/unittests/osm_configurator/model/project/calculation/test_geo_data_phase.py
src_tests/unittests/osm_configurator/model/project/test_active_project.py
src_tests/unittests/osm_configurator/model/project/test_project_io_handler.py

This pull request allows the applciation to create the applciation setting. when bundled as an exe or not. If the file already exsist it wont create a new file.

Application  create application settings

---

src_tests/manualtests/real_world_folder/execution_starting_point.py

execution starting point for tests

---

src/osm_configurator/model/application/application_settings.py

fixed second part of the issue #129.

fixed #129 second part

---

src/osm_configurator/model/project/data_visualizer.py
src/osm_configurator/view/toplevelframes/calculation_frame.py
src/osm_configurator/view/toplevelframes/data_frame.py

#103 Implemented the method so the button should work, not tested yet.

implemented the method to view clacualtion result #103

---

src/osm_configurator/control/application_controller.py
src/osm_configurator/model/application/application.py
src/osm_configurator/model/application/application_settings.py
src_tests/full_application_test/execution_starting_point.py

Application setting when started from execution starting point will now appear randomly anymore.

the applciatio nsetting file can now appear from the position where the file got started from #93

---

src/osm_configurator/model/application/application.py

Fixed that default project list in main menu was always empty.

fixed #142

---

src/osm_configurator/view/utilityframes/reduction_calculation_frame.py

The strictly use default value button worked opposite like it should #120 .

Fix strictly use default value button

---

src/osm_configurator/model/application/application.py
src/osm_configurator/model/parser/category_parser.py
src/osm_configurator/model/project/active_project.py
src/osm_configurator/model/project/configuration/category_manager.py
src/osm_configurator/model/project/export.py
src/osm_configurator/model/project/project_io_handler.py
src/osm_configurator/view/toplevelframes/main_menu_frame.py
src/osm_configurator/view/toplevelframes/project_head_frame.py

Fix #140 and #96

---

src/osm_configurator/view/toplevelframes/attractivity_edit_frame.py

Attractivities should now be selectable without error.

fixed error when selecting attractivity #169

---

src/osm_configurator/model/project/active_project.py
src/osm_configurator/model/project/export.py
src/osm_configurator/model/project/project_io_handler.py
src/osm_configurator/model/project/project_saver.py
src/osm_configurator/model/project/project_settings.py

fixed #117 while #110 fixed itself

Fix useless folder and zip

---

src/osm_configurator/model/parser/category_parser.py
src/osm_configurator/model/project/configuration/category_manager.py
src/osm_configurator/model/project/project_io_handler.py

#106 fixed by checking for "default" when adding the stored default-value-entries during the loading

loading default values #106

---

src/osm_configurator/control/category_controller.py
src/osm_configurator/model/parser/category_parser.py
src/osm_configurator/model/parser/custom_exceptions/not_valid_name_Exception.py
src/osm_configurator/model/project/active_project.py
src/osm_configurator/model/project/configuration/attractivity_attribute.py
src/osm_configurator/model/project/configuration/category.py
src/osm_configurator/model/project/configuration/category_manager.py
src/osm_configurator/model/project/configuration/default_categories.py
src/osm_configurator/view/toplevelframes/attractivity_edit_frame.py
src/osm_configurator/view/toplevelframes/category_frame.py
src/osm_configurator/view/toplevelframes/create_project_frame.py
src/osm_configurator/view/toplevelframes/main_menu_frame.py

Fixed #196 and #190, additonally asci is also only allowed for creating project.

Fix umlauts

---

src/osm_configurator/model/project/configuration/category.py

by adding returns to the activate and deactivate method in category.py

fixxed issue #113 

---

src/osm_configurator/model/project/configuration/category.py
src/osm_configurator/view/toplevelframes/category_frame.py

names can now be changed, also text in black and white list can now be autocompleted with tab button on mac and windows

#198 category name setting fix

---

src/osm_configurator/control/data_visualization_controller.py
src/osm_configurator/control/data_visualization_controller_interface.py
src/osm_configurator/model/project/calculation/paralellization/work_manager.py
src/osm_configurator/model/project/data_visualizer.py
src/osm_configurator/view/toplevelframes/calculation_frame.py

Fix visualize calculation button

---

src/osm_configurator/model/project/data_visualizer.py

deletes folder of boxplot images bevore saving new ones #229

---

src/osm_configurator/model/project/export.py
src_tests/unittests/osm_configurator/model/project/test_project_io_handler.py
src_tests/unittests/osm_configurator/model/project/test_project_saver.py

Fix export

---

src/osm_configurator/model/project/configuration/default_value_entry.py
src/osm_configurator/view/toplevelframes/category_frame.py
src/osm_configurator/view/toplevelframes/reduction_frame.py
src/osm_configurator/view/utilityframes/reduction_default_value_frame.py
src/osm_configurator/view/utilityframes/tag_list_priority_frame.py

Values can be swaped with no prolem now.
Default value has protection to name change.
Frame freezes porplery upon an YesNoPopUp.

#233 default values fix

---

src/osm_configurator/model/project/configuration/category.py
src/osm_configurator/view/toplevelframes/attractivity_edit_frame.py
src/osm_configurator/view/toplevelframes/attractivity_view_frame.py
src/osm_configurator/view/utilityframes/reduction_calculation_frame.py

Reduction Calculation Frame works properly now.
Also Attractivity edit, doesn't struggle with empty list of categories anymore.
Also Attractivity View now shows all labels and sets the innitial button correctly.

Fixxing reduction calculation frame and Attractivity Frame bug fixxes

---

src/osm_configurator/view/toplevelframes/project_head_frame.py

Export has the correct color now

Fixed issue #117

---

src_tests/unittests/osm_configurator/model/application/test_recommender_system.py
src_tests/unittests/osm_configurator/model/project/test_project_io_handler.py
src_tests/unittests/osm_configurator/model/project/test_project_saver.py

Fix unit tests

---

src/osm_configurator/model/application/application_settings.py
src_tests/unittests/osm_configurator/model/application/test_recommender_system.py
src_tests/unittests/osm_configurator/model/project/test_data_visualizer.py

Fix unittest

---

src/osm_configurator/model/project/configuration/attractivity_attribute.py
src/osm_configurator/model/project/configuration/category.py
src/osm_configurator/model/project/configuration/default_value_entry.py
src_tests/unittests/osm_configurator/model/project/configuration/test_aggregation_configuration.py
src_tests/unittests/osm_configurator/model/project/configuration/test_attractivity_attribute.py
src_tests/unittests/osm_configurator/model/project/configuration/test_category.py
src_tests/unittests/osm_configurator/model/project/configuration/test_cut_out_configuration.py
src_tests/unittests/osm_configurator/model/project/configuration/test_default_value_entry.py
src_tests/unittests/osm_configurator/model/project/configuration/test_osm_data_configuration.py

Add unittests config

---

src/osm_configurator/model/project/configuration/attractivity_attribute.py
src/osm_configurator/model/project/configuration/category.py
src/osm_configurator/model/project/configuration/default_value_entry.py
src_tests/unittests/osm_configurator/model/project/configuration/test_aggregation_configuration.py
src_tests/unittests/osm_configurator/model/project/configuration/test_attractivity_attribute.py
src_tests/unittests/osm_configurator/model/project/configuration/test_category.py
src_tests/unittests/osm_configurator/model/project/configuration/test_cut_out_configuration.py
src_tests/unittests/osm_configurator/model/project/configuration/test_default_value_entry.py
src_tests/unittests/osm_configurator/model/project/configuration/test_osm_data_configuration.py

Reverts LuposX/KonfiguratorFuerOSMDaten#247

Revert "Revert "Add unittests config""

---

src/osm_configurator/model/application/application.py
src/osm_configurator/model/application/application_settings.py
src/osm_configurator/model/parser/osm_data_handler.py
src/osm_configurator/model/parser/osm_data_parser_interface.py
src/osm_configurator/model/parser/tag_parser.py
src/osm_configurator/model/project/calculation/aggregation_method_enum.py
src/osm_configurator/model/project/calculation/aggregation_phase.py
src/osm_configurator/model/project/calculation/attractivity_phase.py
src/osm_configurator/model/project/calculation/calculation_phase_interface.py
src/osm_configurator/model/project/calculation/calculation_state_enum.py
src/osm_configurator/model/project/calculation/default_value_finder.py
src/osm_configurator/model/project/calculation/geo_data_phase.py
src/osm_configurator/model/project/calculation/paralellization/work.py
src/osm_configurator/model/project/calculation/paralellization/work_manager.py
src/osm_configurator/model/project/calculation/prepare_calculation_information.py
src/osm_configurator/model/project/calculation/prepare_calculation_phase.py
src/osm_configurator/model/project/calculation/reduction_phase.py
src/osm_configurator/model/project/calculation/tag_filter_phase.py
src/osm_configurator/model/project/configuration/attribute_enum.py
src/osm_configurator/model/project/configuration/category_manager.py
src/osm_configurator/model/project/configuration/default_categories.py
src/osm_configurator/model/project/data_visualizer.py

#219 Removed some redundancy of code by introducing a new class

Reudant code removal model

---

src/osm_configurator/model/application/application.py
src/osm_configurator/model/project/project_io_handler.py
src/osm_configurator/model/project/project_settings.py
src_tests/unittests/osm_configurator/model/application/test_application.py
src_tests/unittests/osm_configurator/model/project/configuration/test_default_value_entry.py
src_tests/unittests/osm_configurator/model/project/test_active_project.py
src_tests/unittests/osm_configurator/model/project/test_project_settings.py

unittests for project settings and project io handler

Extend model unittests

---

src/osm_configurator/control/project_controller.py
src/osm_configurator/control/project_controller_interface.py
src/osm_configurator/model/application/passive_project.py
src/osm_configurator/model/project/active_project.py
src/osm_configurator/model/project/project_io_handler.py
src/osm_configurator/model/project/project_saver.py
src/osm_configurator/view/toplevelframes/main_menu_frame.py

fixed storage of location as discussed in discord

the location of the project is no longer stored

---

src/osm_configurator/model/project/project_settings.py
src_tests/integration_tests/use_case_tests/test_usecase_20_export_results.py
src_tests/integration_tests/use_case_tests/test_usecase_21_export_project.py
src_tests/integration_tests/use_case_tests/test_usecase_22_export.py
src_tests/integration_tests/use_case_tests/test_usecase_23_change_settings.py
src_tests/unittests/osm_configurator/model/project/test_export.py

-usecase 20, 21,22 and 23 done
-code coverage of project settings increased

Use cases 20ff

---

src/osm_configurator/model/project/active_project.py
src/osm_configurator/model/project/configuration/configuration_manager.py
src/osm_configurator/view/toplevelframes/main_menu_frame.py
src_tests/unittests/osm_configurator/model/project/test_project_settings.py

-add test_change_location
-fix last step when loading an external project
-fix #298

Fix some bugs model

---

src/osm_configurator/model/project/calculation/split_up_files.py

This should make it possible to run the programm when not frozen and osmium not installed.

osmium_tool should now work if not frozen and not installed via conda

---

src/osm_configurator/view/toplevelframes/data_frame.py

how does it take so long to fix this small bugg

this should fix #91

---

src/osm_configurator/view/toplevelframes/data_frame.py

#91 wasnt fully fixed, this merge requets fixes this.

fixed for sure now

---

src/osm_configurator/model/project/calculation/split_up_files.py

changed fro mrun to popen subprocess.

changed run to popen so that applciatio ndoesnt freeze

---

src/osm_configurator/model/project/calculation/split_up_files.py

Reverts LuposX/KonfiguratorFuerOSMDaten#312

Revert "changed run to popen so that applciatio ndoesnt freeze"

---

src/osm_configurator/view/toplevelframes/data_frame.py

Data frame asks for directory paths now instead of filenames

Fixed issue 258

---

src/osm_configurator/model/project/export.py
src/osm_configurator/model/project/project_io_handler.py
src/osm_configurator/view/toplevelframes/create_project_frame.py
src/osm_configurator/view/toplevelframes/main_menu_frame.py

fix export and reimport of projects
fix last step
fix pop ups for loading projects

Dev fix load

---

src/osm_configurator/view/toplevelframes/calculation_frame.py
src/osm_configurator/view/toplevelframes/category_frame.py
src/osm_configurator/view/toplevelframes/main_menu_frame.py
src/osm_configurator/view/utility_methods.py
src/osm_configurator/view/utilityframes/reduction_calculation_frame.py
src/osm_configurator/view/utilityframes/settings_application_frame.py
src_tests/unittests/osm_configurator/view/utility_methods_tests/test_utility_methods.py

A lot of issues have been fixxed

View issues

---

src/osm_configurator/view/toplevelframes/calculation_frame.py
src/osm_configurator/view/toplevelframes/category_frame.py
src/osm_configurator/view/toplevelframes/main_menu_frame.py
src/osm_configurator/view/utility_methods.py
src/osm_configurator/view/utilityframes/reduction_calculation_frame.py
src/osm_configurator/view/utilityframes/settings_application_frame.py
src_tests/unittests/osm_configurator/view/utility_methods_tests/test_utility_methods.py

Reverts LuposX/KonfiguratorFuerOSMDaten#316

Revert "Revert "View issues""

---

src/osm_configurator/control/category_controller.py
src/osm_configurator/view/toplevelframes/data_frame.py
src/osm_configurator/view/toplevelframes/project_head_frame.py

Fix issues in category import and osm selection

---

src/osm_configurator/view/popups/yes_no_pop_up.py

Alert Popup now is called "Please select" instead of "CTkTopLevel"

Fixed issue #157; Changed names of popups

---

src/osm_configurator/view/popups/alert_pop_up.py
src/osm_configurator/view/utilityframes/reduction_calculation_frame.py

replaced button width and height adjusted to screen now adjusts has the value of the constant enum now

Buttons are fine now i swear

---

src/osm_configurator/model/project/active_project.py
src/osm_configurator/model/project/calculation/paralellization/work_manager.py

fix calcultation on windows 11
remove print statement

Fix calc windows 11

---

src_tests/manualtests/osm_configurator/view/controller_stub/project_controller_stub.py
src_tests/manualtests/osm_configurator/view/controller_stub/settings_controller_stub.py
src_tests/unittests/osm_configurator/view/states/test_main_window.py
src_tests/unittests/osm_configurator/view/states/test_positioned_frame.py
src_tests/unittests/osm_configurator/view/states/test_state.py
src_tests/unittests/osm_configurator/view/states/test_state_manager.py
src_tests/unittests/osm_configurator/view/states/top_level_frame_stub.py

View test added to the most current dev

addes view tests
